### ISSUE TITLE
Where to find the statistical info?

### ISSUE THREAD

**Issue by heejongkim** [ScheltemaLab/ChimeraX_XMAS_bundle#1]
Hello,

Thank you so much for developing such fantastic addon for chimeraX.

I'm wondering where I can find those values plotted in distance plot.
I see, from the log, unique peptide pairs and unique peptide pairs with pseudobonds.
I believe those corresponding to unique unique peptide sequence pairs (not necessarily residue pairs) and with pseudobonds means XLs that are mapped to the model.

I wonder what would be the best way to get numbers of unique pairs with distance cutoff so I can tell how many agree or disagree quickly and accurately.

Thank you so much.

**Comment by rscheltema** [comment]
Hi,

Appologies for the ultra-late reply; we didn't notice this (?). If this is still current. A .TSV file is generated in the same folder as the crosslinks file you load, where all the distances are displayed.

Cheers, Richard
